# # Use root/example as user/password credentials
# version: '3.1'
# services:

#   DB1:
#     image: mongo:latest
#     restart: always
#     ports:
#       - "21017:27017"
#     env_file:
#       - .env
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USR}
#       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PWD}
#       MONGO_INITDB_DATABASE: whiskers
#     volumes:
#       - dbdata6:/data/db

#   DB2:
#     image: mongo:latest
#     restart: always
#     ports:
#       - "27018:27018"
#     env_file:
#       - .env
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USR}
#       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PWD}
#       MONGO_INITDB_DATABASE: whiskers
#     volumes:
#       - dbdata7:/data/db

# volumes:
#   dbdata6:
#   dbdata7:

version: '3.4'

services:
  mongo-container-1:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USR}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PWD}
      - MONGO_INITDB_DATABASE=database
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb1_data:/data/db
    command: mongod --auth

  mongo-container-2:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USR}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PWD}
      - MONGO_INITDB_DATABASE=database
    env_file:
      - .env
    ports:
      - "27018:27017" # Mapeando para uma porta diferente
    volumes:
      - mongodb2_data:/data/db
    command: mongod --auth

volumes:
  mongodb1_data:
  mongodb2_data:
