# Use root/example as user/password credentials
version: '3.1'
services:

  DB:
    image: mongo:latest
    restart: always
    ports:
      - "21017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USR}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PWD}
      MONGO_INITDB_DATABASE: whiskers
    volumes:
      - dbdata6:/data/db

volumes:
  dbdata6: